query GetLayers($mapId: ObjectId!) {
    layers(mapId: $mapId) {
        _id
        name
        description
        configuration
        access
        color
        owner {
            role
        }
    }
}
