#import "../AccessSettings/query.gql"

fragment AccessFragment on Access {
    view {
        ...AccessSettings
    }
    comment {
        ...AccessSettings
    }
    edit {
        ...AccessSettings
    }
}
